import type PptxGenJSType from "pptxgenjs";
import type { TripPlan, TripActivity } from "@/types/trip-plan";

const PRIMARY = "6366f1";
const PRIMARY_DARK = "4f46e5";
const WHITE = "FFFFFF";
const DARK_TEXT = "1e293b";
const MUTED = "64748b";
const LIGHT_BG = "f8fafc";
const ACCENT_BG = "eef2ff";

type Prs = InstanceType<typeof PptxGenJSType>;
type Slide = PptxGenJSType.Slide;

export async function generateTripPPT(plan: TripPlan, destination: string): Promise<void> {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const prs: Prs = new PptxGenJS();

  prs.layout = "LAYOUT_16x9";
  prs.title = `${plan.destination || destination} – Planzo.ai Itinerary`;
  prs.subject = "Trip Itinerary";
  prs.author = "Planzo.ai";

  // ── SLIDE 1: Cover ──────────────────────────────────────────────
  const cover = prs.addSlide();
  cover.background = { color: PRIMARY };

  cover.addText("✈️ Planzo.ai", {
    x: 0.5, y: 0.4, w: "90%", h: 0.5,
    fontSize: 16, color: "c7d2fe", bold: false, fontFace: "Segoe UI",
  });

  cover.addText(plan.destination || destination, {
    x: 0.5, y: 1.1, w: "90%", h: 1.5,
    fontSize: 44, bold: true, color: WHITE, fontFace: "Segoe UI",
    wrap: true,
  });

  if (plan.summary) {
    cover.addText(plan.summary, {
      x: 0.5, y: 2.8, w: "90%", h: 1.6,
      fontSize: 14, color: "e0e7ff", fontFace: "Segoe UI", wrap: true,
    });
  }

  cover.addText("Generated by Planzo.ai — Your Smart Trip Planner", {
    x: 0.5, y: 4.9, w: "90%", h: 0.4,
    fontSize: 10, color: "a5b4fc", fontFace: "Segoe UI",
  });

  // ── SLIDE 2: Trip Overview ───────────────────────────────────────
  if (plan.itinerary || plan.budgetBreakdown || plan.weatherNote) {
    const overview = prs.addSlide();
    overview.background = { color: LIGHT_BG };

    addSlideHeader(overview, prs, "Trip Overview");

    const items: string[] = [];
    if (plan.itinerary) items.push(`📅 ${plan.itinerary.length} Days`);
    if (plan.budget?.total) items.push(`💰 Budget: ₹${Number(plan.budget.total).toLocaleString("en-IN")}`);
    if (plan.vibe) items.push(`🎭 Vibe: ${plan.vibe}`);
    if (plan.weatherNote) items.push(`🌤 ${plan.weatherNote}`);
    if (plan.travelOptions && plan.travelOptions.length > 0) {
      const opt = plan.travelOptions[0];
      items.push(`🚂 Travel: ${opt.mode || ""} – ${opt.from || ""} → ${opt.to || ""}`);
    }

    items.forEach((text, i) => {
      overview.addText(text, {
        x: 0.6, y: 1.3 + i * 0.65, w: "88%", h: 0.55,
        fontSize: 15, color: DARK_TEXT, fontFace: "Segoe UI",
        bullet: false,
      });
    });
  }

  // ── SLIDES 3+: One slide per day ─────────────────────────────────
  if (plan.itinerary) {
    for (const day of plan.itinerary) {
      const slide = prs.addSlide();
      slide.background = { color: WHITE };

      // Day header band
      slide.addShape(prs.ShapeType.rect, {
        x: 0, y: 0, w: "100%", h: 1.0,
        fill: { color: PRIMARY },
      });

      slide.addText(`Day ${day.day}`, {
        x: 0.4, y: 0.05, w: 1.2, h: 0.4,
        fontSize: 13, bold: true, color: "c7d2fe", fontFace: "Segoe UI",
      });

      slide.addText(day.title || `Day ${day.day}`, {
        x: 0.4, y: 0.42, w: "88%", h: 0.52,
        fontSize: 22, bold: true, color: WHITE, fontFace: "Segoe UI",
      });

      let yPos = 1.2;

      // Activities
      if (day.activities && day.activities.length > 0) {
        day.activities.slice(0, 6).forEach((act: TripActivity | string, j: number) => {
          const label =
            typeof act === "string"
              ? act
              : [act.name, act.place ? `— ${act.place}` : ""].filter(Boolean).join(" ");

          slide.addText(`${j + 1}.  ${label}`, {
            x: 0.5, y: yPos, w: "88%", h: 0.42,
            fontSize: 13, color: DARK_TEXT, fontFace: "Segoe UI", wrap: true,
          });
          yPos += 0.44;
        });
      }

      // Meals row
      if (day.meals) {
        yPos += 0.1;
        const mealsText = Object.entries(day.meals)
          .map(([m, s]) => `${m.charAt(0).toUpperCase() + m.slice(1)}: ${s}`)
          .join("   •   ");

        slide.addShape(prs.ShapeType.rect, {
          x: 0.4, y: yPos, w: "88%", h: 0.5,
          fill: { color: "f0fdf4" }, line: { color: "bbf7d0", width: 1 },
        });
        slide.addText(`🍽  ${mealsText}`, {
          x: 0.5, y: yPos + 0.06, w: "86%", h: 0.4,
          fontSize: 10, color: "166534", fontFace: "Segoe UI", wrap: true,
        });
        yPos += 0.6;
      }

      // Tip
      if (day.tips) {
        slide.addText(`💡 Tip: ${day.tips}`, {
          x: 0.5, y: yPos, w: "88%", h: 0.4,
          fontSize: 10, color: PRIMARY_DARK, fontFace: "Segoe UI",
          italic: true, wrap: true,
        });
      }
    }
  }

  // ── SLIDE: Budget Breakdown ──────────────────────────────────────
  if (plan.budgetBreakdown) {
    const bdg = prs.addSlide();
    bdg.background = { color: LIGHT_BG };

    addSlideHeader(bdg, prs, "💰 Budget Breakdown");

    const entries = Object.entries(plan.budgetBreakdown)
      .filter(([, v]) => typeof v === "number" && v > 0) as [string, number][];

    const total = entries.reduce((s, [, v]) => s + v, 0);

    entries.forEach(([key, val], i) => {
      const label = key.charAt(0).toUpperCase() + key.slice(1);
      const pct = total > 0 ? Math.round((val / total) * 100) : 0;
      const barW = Math.max(0.1, (val / total) * 7);

      const yBase = 1.3 + i * 0.72;

      bdg.addText(label, {
        x: 0.5, y: yBase, w: 2.0, h: 0.35,
        fontSize: 13, bold: true, color: DARK_TEXT, fontFace: "Segoe UI",
      });

      bdg.addShape(prs.ShapeType.rect, {
        x: 2.6, y: yBase + 0.07, w: barW, h: 0.2,
        fill: { color: PRIMARY }, line: { color: PRIMARY, width: 0 },
      });

      bdg.addText(`₹${val.toLocaleString("en-IN")}  (${pct}%)`, {
        x: 2.7 + barW, y: yBase, w: 3.0, h: 0.35,
        fontSize: 12, color: MUTED, fontFace: "Segoe UI",
      });
    });

    if (total > 0) {
      bdg.addText(`Total estimated: ₹${total.toLocaleString("en-IN")}`, {
        x: 0.5, y: 4.8, w: "88%", h: 0.4,
        fontSize: 13, bold: true, color: DARK_TEXT, fontFace: "Segoe UI",
      });
    }
  }

  // ── SLIDE: Packing List ──────────────────────────────────────────
  if (plan.packingList && plan.packingList.length > 0) {
    const pack = prs.addSlide();
    pack.background = { color: ACCENT_BG };

    addSlideHeader(pack, prs, "🎒 Packing List");

    const half = Math.ceil(plan.packingList.length / 2);
    const col1 = plan.packingList.slice(0, half);
    const col2 = plan.packingList.slice(half);

    col1.forEach((item, i) => {
      pack.addText(`• ${item}`, {
        x: 0.5, y: 1.25 + i * 0.45, w: 4.5, h: 0.4,
        fontSize: 12, color: DARK_TEXT, fontFace: "Segoe UI",
      });
    });

    col2.forEach((item, i) => {
      pack.addText(`• ${item}`, {
        x: 5.2, y: 1.25 + i * 0.45, w: 4.5, h: 0.4,
        fontSize: 12, color: DARK_TEXT, fontFace: "Segoe UI",
      });
    });
  }

  // ── SLIDE: Safety Tips ───────────────────────────────────────────
  if (plan.safetyTips && plan.safetyTips.length > 0) {
    const safety = prs.addSlide();
    safety.background = { color: "fffbeb" };

    addSlideHeader(safety, prs, "🛡 Safety Tips");

    plan.safetyTips.slice(0, 6).forEach((tip, i) => {
      safety.addText(`⚠️  ${tip}`, {
        x: 0.5, y: 1.25 + i * 0.65, w: "88%", h: 0.55,
        fontSize: 13, color: "92400e", fontFace: "Segoe UI", wrap: true,
      });
    });
  }

  // ── SLIDE: Thank-you ─────────────────────────────────────────────
  const thanks = prs.addSlide();
  thanks.background = { color: PRIMARY };

  thanks.addText("Safe Travels! ✈️", {
    x: 0, y: 1.8, w: "100%", h: 1.0,
    fontSize: 40, bold: true, color: WHITE,
    fontFace: "Segoe UI", align: "center",
  });

  thanks.addText("Generated by Planzo.ai — planzo.ai", {
    x: 0, y: 3.2, w: "100%", h: 0.4,
    fontSize: 13, color: "c7d2fe",
    fontFace: "Segoe UI", align: "center",
  });

  // ── Save ─────────────────────────────────────────────────────────
  await prs.writeFile({
    fileName: `${plan.destination || destination || "trip"}-itinerary.pptx`,
  });
}

function addSlideHeader(slide: Slide, prs: Prs, title: string): void {
  slide.addShape(prs.ShapeType.rect, {
    x: 0, y: 0, w: "100%", h: 0.9,
    fill: { color: PRIMARY },
  });
  slide.addText(title, {
    x: 0.5, y: 0.12, w: "88%", h: 0.65,
    fontSize: 22, bold: true, color: WHITE, fontFace: "Segoe UI",
  });
}
