import { forwardRef } from "react";
import type { TripPlan, TripActivity } from "@/types/trip-plan";

interface TripPDFProps {
  plan: TripPlan;
  destination: string;
}

const TripPDF = forwardRef<HTMLDivElement, TripPDFProps>(({ plan, destination }, ref) => {
  const styles = {
    container: {
      fontFamily: "'Plus Jakarta Sans', 'Segoe UI', sans-serif",
      color: "#1a1a2e",
      padding: "32px",
      maxWidth: "800px",
      margin: "0 auto",
      background: "#fff",
    } as React.CSSProperties,
    header: {
      textAlign: "center" as const,
      marginBottom: "24px",
      borderBottom: "3px solid #6366f1",
      paddingBottom: "20px",
    } as React.CSSProperties,
    title: {
      fontSize: "28px",
      fontWeight: 800,
      color: "#6366f1",
      margin: 0,
    } as React.CSSProperties,
    subtitle: {
      fontSize: "13px",
      color: "#64748b",
      marginTop: "6px",
    } as React.CSSProperties,
    summary: {
      fontSize: "14px",
      color: "#475569",
      lineHeight: 1.6,
      marginTop: "12px",
    } as React.CSSProperties,
    sectionTitle: {
      fontSize: "18px",
      fontWeight: 700,
      color: "#1e293b",
      marginTop: "28px",
      marginBottom: "12px",
      borderLeft: "4px solid #6366f1",
      paddingLeft: "12px",
    } as React.CSSProperties,
    dayCard: {
      border: "1px solid #e2e8f0",
      borderRadius: "12px",
      padding: "16px",
      marginBottom: "16px",
      background: "#fafbfc",
    } as React.CSSProperties,
    dayTitle: {
      fontSize: "16px",
      fontWeight: 700,
      color: "#6366f1",
      marginBottom: "10px",
    } as React.CSSProperties,
    activity: {
      fontSize: "13px",
      color: "#334155",
      padding: "4px 0",
      paddingLeft: "12px",
      borderLeft: "2px solid #e2e8f0",
      marginBottom: "4px",
    } as React.CSSProperties,
    meals: {
      fontSize: "12px",
      color: "#64748b",
      marginTop: "8px",
      padding: "8px 12px",
      background: "#f1f5f9",
      borderRadius: "8px",
    } as React.CSSProperties,
    tip: {
      fontSize: "12px",
      color: "#6366f1",
      fontStyle: "italic" as const,
      marginTop: "6px",
    } as React.CSSProperties,
    budgetTable: {
      width: "100%",
      borderCollapse: "collapse" as const,
      fontSize: "13px",
      marginTop: "8px",
    } as React.CSSProperties,
    th: {
      textAlign: "left" as const,
      padding: "8px 12px",
      background: "#6366f1",
      color: "#fff",
      fontWeight: 600,
    } as React.CSSProperties,
    td: {
      padding: "8px 12px",
      borderBottom: "1px solid #e2e8f0",
    } as React.CSSProperties,
    list: {
      fontSize: "13px",
      color: "#475569",
      paddingLeft: "20px",
      lineHeight: 1.8,
    } as React.CSSProperties,
    footer: {
      textAlign: "center" as const,
      marginTop: "32px",
      paddingTop: "16px",
      borderTop: "2px solid #e2e8f0",
      fontSize: "11px",
      color: "#94a3b8",
    } as React.CSSProperties,
  };

  const budgetBreakdown = plan.budgetBreakdown;
  const budgetEntries = budgetBreakdown
    ? Object.entries(budgetBreakdown).map(([key, val]) => ({
        label: key.charAt(0).toUpperCase() + key.slice(1),
        value: typeof val === "number" ? `₹${val.toLocaleString("en-IN")}` : String(val ?? "—"),
      }))
    : [];

  return (
    <div ref={ref} style={styles.container}>
      {/* Header */}
      <div style={styles.header}>
        <h1 style={styles.title}>📍 {plan.destination || destination}</h1>
        <p style={styles.subtitle}>Generated by Planzo AI • Your Smart Trip Planner</p>
        {plan.summary && <p style={styles.summary}>{plan.summary}</p>}
      </div>

      {/* Weather */}
      {plan.weatherNote && (
        <div style={{ ...styles.dayCard, background: "#eff6ff" }}>
          <strong style={{ fontSize: "13px" }}>🌤 Weather:</strong>{" "}
          <span style={{ fontSize: "13px", color: "#475569" }}>{plan.weatherNote}</span>
        </div>
      )}

      {/* Itinerary */}
      {plan.itinerary && plan.itinerary.length > 0 && (
        <>
          <h2 style={styles.sectionTitle}>📋 Day-by-Day Itinerary</h2>
          {plan.itinerary.map((day) => (
            <div key={day.day} style={styles.dayCard}>
              <h3 style={styles.dayTitle}>
                Day {day.day}: {day.title}
              </h3>
              {day.activities &&
                day.activities.map((act: TripActivity | string, j: number) => (
                  <div key={j} style={styles.activity}>
                    {typeof act === "string"
                      ? act
                      : `${act.name}${act.place ? ` — ${act.place}` : ""}`}
                  </div>
                ))}
              {day.meals && (
                <div style={styles.meals}>
                  🍽 <strong>Meals:</strong> Breakfast: {day.meals.breakfast} • Lunch:{" "}
                  {day.meals.lunch} • Dinner: {day.meals.dinner}
                </div>
              )}
              {day.tips && <p style={styles.tip}>💡 Tip: {day.tips}</p>}
            </div>
          ))}
        </>
      )}

      {/* Budget */}
      {budgetEntries.length > 0 && (
        <>
          <h2 style={styles.sectionTitle}>💰 Budget Breakdown</h2>
          <table style={styles.budgetTable}>
            <thead>
              <tr>
                <th style={styles.th}>Category</th>
                <th style={{ ...styles.th, textAlign: "right" }}>Estimated Cost</th>
              </tr>
            </thead>
            <tbody>
              {budgetEntries.map((e) => (
                <tr key={e.label}>
                  <td style={styles.td}>{e.label}</td>
                  <td style={{ ...styles.td, textAlign: "right", fontWeight: 600 }}>{e.value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </>
      )}

      {/* Travel Options */}
      {plan.travelOptions && plan.travelOptions.length > 0 && (
        <>
          <h2 style={styles.sectionTitle}>🚂 Travel Options</h2>
          {plan.travelOptions.map((opt, i) => (
            <div key={i} style={styles.activity}>
              <strong>{opt.mode}</strong>: {opt.from} → {opt.to} • ~₹
              {typeof opt.estimatedCost === "number" ? opt.estimatedCost.toLocaleString("en-IN") : opt.estimatedCost} • {opt.duration}
            </div>
          ))}
        </>
      )}

      {/* Packing List */}
      {plan.packingList && plan.packingList.length > 0 && (
        <>
          <h2 style={styles.sectionTitle}>🎒 Packing List</h2>
          <ul style={styles.list}>
            {plan.packingList.map((item, i) => (
              <li key={i}>{item}</li>
            ))}
          </ul>
        </>
      )}

      {/* Safety Tips */}
      {plan.safetyTips && plan.safetyTips.length > 0 && (
        <>
          <h2 style={styles.sectionTitle}>🛡 Safety Tips</h2>
          <ul style={styles.list}>
            {plan.safetyTips.map((tip, i) => (
              <li key={i}>{tip}</li>
            ))}
          </ul>
        </>
      )}

      {/* Footer */}
      <div style={styles.footer}>
        <p>Generated by Planzo AI — planzo.ai</p>
        <p>Share this plan with your travel buddies! ✈️</p>
      </div>
    </div>
  );
});

TripPDF.displayName = "TripPDF";

export default TripPDF;
