// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

export const hasSupabaseConfig =
  SUPABASE_URL.startsWith('http') && SUPABASE_PUBLISHABLE_KEY.length > 20;

export const supabaseConfigError = hasSupabaseConfig
  ? null
  : "Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file and restart dev server.";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const createMissingConfigClient = () => {
  return new Proxy({} as SupabaseClient<Database>, {
    get() {
      throw new Error(supabaseConfigError ?? 'Supabase is not configured.');
    }
  });
};

export const supabase = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createMissingConfigClient();